### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by flydragon2018** [MarioRuggieri/Emotion-Recognition-from-Speech#6]
Loading data from berlin dataset...
Error in readAudioFile(): Unknown file type!
Traceback (most recent call last):
  File "emorecognition.py", line 41, in <module>
    db = Dataset(path,db_type,decode=False)
  File "/home/zzl/Emotion-Recognition-from-Speech/src/dataset.py", line 18, in __init__
    self.get_berlin_dataset(path)
  File "/home/zzl/Emotion-Recognition-from-Speech/src/dataset.py", line 35, in get_berlin_dataset
    self.targets.append(classes[audio[5]])
IndexError: string index out of range

**Comment by returnWOW** [comment]
You  need enter a correct file path, I use the path download\wav is work fine.
Sorry foy my bad English.
